[checkcommit] Fix logic for --skip-checkcommit and --force-checkcommit #86
This check is run when any of the following conditions is true:
1. --force-checkcommit is specified
2. This function is invoked from Travis building a Pull Request

Related to #86

diff --git a/openwisp-utils-qa-checks b/openwisp-utils-qa-checks
--- a/openwisp-utils-qa-checks
+++ b/openwisp-utils-qa-checks
@@ -20,7 +20,7 @@ show_help() {
   printf "\t\t\t\t  say, if checking needs to start after 0003_auto_20150410_3242.py value should be 3\n"
   printf "  --skip-checkmigrations\t: Skip migration name check\n"
   printf "  You can do multiple migration check by passing the arguments with space-delimited string array.\n"
-  printf "Commit name check options:\n"
+  printf "Commit message check options:\n"
   printf "  --message <commit-message>\t: Commit message (by default is equal to latest commit name)\n"
   printf "  --migration-module <module>\t: Name of Migration Module\n"
   printf "  --skip-checkmakemigrations\t: Skip make migration check\n"
@@ -83,15 +83,18 @@ runisort() {
     || { echoerr "ERROR: Isort check failed!"; FAILURE=1; }
 }
 
+# This check is run when any of the following conditions is true:
+# 1. --force-checkcommit is specified
+# 2. This function is invoked from Travis building a Pull Request
 runcheckcommit() {
-  [ -n "$TRAVIS_PULL_REQUEST" ] || TRAVIS_PULL_REQUEST="false"
-  if [ "$SKIP_CHECKCOMMIT" = "false" -o "$TRAVIS_PULL_REQUEST" != "false" ]; then
+  [ -n "$TRAVIS_PULL_REQUEST" ] || TRAVIS_PULL_REQUEST=false
+  if [[ $FORCE_CHECKCOMMIT = true ]] || [[ $TRAVIS_PULL_REQUEST = true ]]; then
     echo "Running commit message check"
     checkcommit --message "$COMMIT_MESSAGE" \
-    && echo "SUCCESS: Commit name check successful!" \
-    || { printf "Checking commit message:\n\n"; printf "%s\n\n" "$COMMIT_MESSAGE"; echoerr "ERROR: Commit name check failed!"; FAILURE=1; }
+    && echo "SUCCESS: Commit message check successful!" \
+    || { printf "Checking commit message:\n\n"; printf "%s\n\n" "$COMMIT_MESSAGE"; echoerr "ERROR: Commit message check failed!"; FAILURE=1; }
   else
-    echo "SUCCESS: Commit name check successful!"
+    echo "SKIPPED: Commit message check"
   fi
 }
 
@@ -115,6 +118,7 @@ SKIP_MAKEMIGRATIONS=false
 SKIP_FLAKE8=false
 SKIP_ISORT=false
 SKIP_CHECKCOMMIT=false
+FORCE_CHECKCOMMIT=false
 MIGRATION_PATH=""
 MIGRATIONS_TO_IGNORE="0"
 COMMIT_MESSAGE=$(git log $TRAVIS_PULL_REQUEST_SHA --format=%B -n 1)
@@ -147,7 +151,7 @@ while [ "$1" != "" ]; do
     SKIP_CHECKCOMMIT=true
     ;;
   --force-checkcommit)
-    SKIP_CHECKCOMMIT=false
+    FORCE_CHECKCOMMIT=true
     ;;
   --message)
     shift
